# Generated by Django 3.2.5 on 2021-07-18 08:09

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('job', models.CharField(max_length=100, verbose_name='Job')),
                ('email', models.CharField(max_length=150, verbose_name='E-mail')),
                ('domain_name', models.CharField(max_length=100, verbose_name='Domain name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company name')),
                ('text', models.TextField(verbose_name='Text')),
                ('integer', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Integer')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Schemas',
                'verbose_name_plural': 'Schema',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExportToCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PROGRESS', 'In progress')], default='NEW', max_length=8)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='export/csv/%Y/%m/%d', verbose_name='CSV file')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Export to CSV',
                'verbose_name_plural': 'Exports to CSV',
                'ordering': ['-id'],
            },
        ),
    ]
